---
ping_exporter_download_url: https://raw.githubusercontent.com/acjohnson/ping-exporter/refs/heads/master/ping-exporter.py
ping_exporter_checksum: sha256:7a9ed671ba35c95815eee39dad641e7ce596b05382776e875ca7fc236b064a00
